[package]
name = "solana-remote-keypair"
description = "Solana utilies for non-wallet hardware tokens"
documentation = "https://docs.rs/solana-remote-keypair"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = { workspace = true }
openpgp-card = { workspace = true }
openpgp-card-pcsc = { workspace = true, optional = true }
pinentry = { workspace = true }
secrecy = { workspace = true }
solana-sdk = { workspace = true }
thiserror = { workspace = true }
uriparse = { workspace = true }

[features]
pcsc = ["openpgp-card-pcsc"]

[lib]
name = "solana_remote_keypair"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
